### ISSUE TITLE
Installation error when running composer install

### ISSUE THREAD

**Issue by brandonkyaw** [LaravelDaily/Laravel-Restaurant-Menu#1]
I'm the following the instructions to clone this project and I seem to get a few errors when running `composer install`. Any ideas why this is occurring?

  **Problem 1**
    - Installation request for laravel/dusk v5.11.0 -> satisfiable by laravel/dusk[v5.11.0].
    - laravel/dusk v5.11.0 requires ext-zip * -> the requested PHP extension zip is missing from your system.

  **Problem 2**
    - Installation request for php-webdriver/webdriver 1.8.2 -> satisfiable by php-webdriver/webdriver[1.8.2].
    - php-webdriver/webdriver 1.8.2 requires ext-zip * -> the requested PHP extension zip is missing from your system.

  **Problem 3**
    - Installation request for spatie/pdf-to-image 2.0.1 -> satisfiable by spatie/pdf-to-image[2.0.1].
    - spatie/pdf-to-image 2.0.1 requires ext-imagick * -> the requested PHP extension imagick is missing from your system.

  **Problem 4**
    - spatie/pdf-to-image 2.0.1 requires ext-imagick * -> the requested PHP extension imagick is missing from your system.
    - spatie/laravel-medialibrary 7.19.3 requires spatie/pdf-to-image ^2.0 -> satisfiable by spatie/pdf-to-image[2.0.1].
    - Installation request for spatie/laravel-medialibrary 7.19.3 -> satisfiable by spatie/laravel-medialibrary[7.19.3].

**Comment by PovilasKorop** [comment]
@brandonkyaw well, errors are pretty clear:

- the requested PHP extension zip is missing from your system.
- the requested PHP extension imagick is missing from your system.

So, install/enable those PHP extensions.
